pipeline {
    agent {
        docker {
            image 'python:2.7.17-alpine3.11'
        }
    }

    stages {

        stage('build') {
            steps {
                echo 'Compilando ....'
                dir(vote){
                    sh 'pip install -i requirements.txt'
                }

            }
        
        stage('test'){
            steps {
                echo 'Testing ...'
                dir(vote){
                    sh 'nosetest -v'
                }


            }
        }

        }
    }

     post{

        always{
            echo 'Pipeline terminado ...'
        }
    }

}

}