pipeline {
    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }

    stages{

        stage('build'){
            steps{
                echo 'Compilando ....'
                dir(vote){
                    sh 'pip install -r requirements.txt'
                }

            }
        }    
        
        stage('test'){
            steps {
                echo 'Testing ...'
                dir(vote){
                    sh 'nosetests -v'
                }


            }
        }

    
    }

     post{

        always{
            echo 'Pipeline terminado ...'
        }
    }

}

