pipeline {

    agent {

        docker {
           image 'maven:3.6.3-openjdk-16-slim'
           args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages{

        stage('build'){
            steps{
                echo 'Compilando worker app ...'
                dir('worker'){
                sh 'mvn compile'
                }
            }
                
        }

        stage('Testing'){
            steps{

                echo 'Testing worker app ...'
                dir('worker'){
                sh 'mvn clean test'
                }

            }
                
        }

        stage('Package'){
            when{
                    
                    changeset "**/worker/**"
                }
            steps{
                
                echo 'generando binario worker app ...'
                dir('worker'){
                sh 'mvn package -DskipTest'
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true

                }
            }
                
        }


    stage('docker-package'){

            steps{
                
                echo 'generando binario worker app ...'
                script{
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {
                        def workerImage = docker.build("peterfunk/worker:${env.BUILD_ID}")
                        workerImage.push("${env.BRANCH_NAKME}")

                    }
                }

                }
            }    

    }

    
}

    

